name: run-playwright-example-tests

on: [push, pull_request]

jobs:
  testApp:
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          shard: [1/3, 2/3, 3/3]
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: 20

        - name: Install Dependencies
          run: npm ci

        - name: Install Playwright browsers
          run: npx playwright install --with-deps

        - name: Run Tests
          run: npx playwright test --shard=${{ matrix.shard }} --reporter=blob
        

         
